call plug#begin()
Plug 'arcticicestudio/nord-vim'
Plug 'junegunn/goyo.vim'
Plug 'preservim/nerdtree'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'xarthurx/taskwarrior.vim'
call plug#end()


" theme
colorscheme nord
highlight Visual ctermbg=Blue ctermfg=Black

" show line numbers
set number 

" Change cursor shape between insert and normal mode 
let &t_SI = "\e[5 q"
let &t_EI = "\e[1 q"

" clipboard (so that yank goes to OS clipboard)
set clipboard=unnamed

" Reset cursor on startup
" because the cursor is coming in insert mode from tmux/bash
" https://vi.stackexchange.com/a/21673
augroup ResetCursorShape
au!
autocmd VimEnter * :normal :startinsert :stopinsert
augroup END



" SHORTCUTS
" leader key
let mapleader = "§"

" pane management
nmap <Leader>- <C-w>s
nmap <Leader>\| <C-w>v
nmap <Leader>j <C-w>j
nmap <Leader>k <C-w>k
nmap <Leader>h <C-w>h
nmap <Leader>l <C-w>l

" toggle nerdtree
nmap <Leader>o :NERDTreeToggle<CR>

" toggle goyo mode
nmap <Leader>g :Goyo<CR>

" toggle taskwarrior
nmap <Leader>t : TW<CR>
