call plug#begin()
Plug 'arcticicestudio/nord-vim'
Plug 'gabrielelana/vim-markdown'
Plug 'godlygeek/tabular'
Plug 'preservim/nerdtree'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
call plug#end()



" theme
colorscheme nord
highlight Visual ctermbg=Blue ctermfg=Black



" show line numbers
set number 
" soft tabs
set tabstop=2 shiftwidth=2 expandtab
" backspace behavior
set backspace=2
" text wrap
" https://vim.fandom.com/wiki/Word_wrap_without_line_breaks
set wrap
set linebreak
set columns=80



" change cursor shape between insert and normal mode 
let &t_SI = "\e[5 q"
let &t_EI = "\e[1 q"

" clipboard (so that yank goes to OS clipboard)
set clipboard=unnamed



" Reset cursor on startup
" because the cursor is coming in insert mode from tmux/bash
" https://vi.stackexchange.com/a/21673
augroup ResetCursorShape
au!
autocmd VimEnter * :normal :startinsert :stopinsert
augroup END



" MARKDOWN
" don't fold chapters
set nofoldenable



" SHORTCUTS
" leader key
let mapleader = "§"

" pane management
nmap <Leader>- <C-w>s
nmap <Leader>\| <C-w>v
nmap <Leader>j <C-w>j
nmap <Leader>k <C-w>k
nmap <Leader>h <C-w>h
nmap <Leader>l <C-w>l

" toggle nerdtree
nmap <Leader>o :NERDTreeToggle<CR>
